<?php
/**
 * Veralidity, LLC
 *
 * @package    Veralidity
 * @category   CardanoDbSync
 * @copyright  Copyright © 2024 Veralidity, LLC
 * @license    https://www.veralidity.com/license/
 * @author     Veralidity, LLC <veralidity@protonmail.com>
 */
?>

<div class="html-desc">
    <p>The purpose of Cardano DB Sync is to follow the Cardano chain and take information from the chain and an internally maintained copy of ledger state. Data is then extracted from the chain and inserted into a PostgreSQL database. SQL queries can then be written directly against the database schema or as queries embedded in any language with libraries for interacting with an SQL database.</p>
    <p>Examples of what someone would be able to do via an SQL query against a Cardano DB Sync instance fully synced to a specific network is:</p>
    <ul>
        <li>Look up any block, transaction, address, stake pool etc on that network, usually by the hash that identifies that item or the index into another table.</li>
        <li>Look up the balance of any stake address for any Shelley or later epoch.</li>
        <li>Look up the amount of ADA delegated to each pool for any Shelley or later epoch.</li>
    </ul>
    <p>For more information please visit: <a href="https://github.com/IntersectMBO/cardano-db-sync" target="_blank" title="Cardano DbSync GitHub">Cardano DbSync GitHub</a></p>
</div>
<div class="html-demeter">
    <h4>Don't want to run your own infrastructure?</h4>
    <p>Effortlessly set up and deploy Cardano DB Sync using Demeter. All you have to do is sign-up and deploy a Cardano DB Sync resource to get your PostgreSQL connection settings.</p>
    <?php $demeterLogo = $block->getViewFileUrl('Veralidity_CardanoDbSync::images/integrations/demeter/demeter-imagotype-horizontal-black.png'); ?>
    <p>
        <a title="Deploy Cardano DB Sync on Demeter" href="https://demeter.run/extensions/cardano-dbsync-port" target="_blank">
            <img src="<?php echo $demeterLogo ?>" alt="Demeter" width="150" />
        </a>
    </p>
    <p>
        <a class="button" id="veraliditycardanodbsync_connection_preview_test_connect_wizard" title="Deploy Cardano DB Sync on Demeter" href="https://demeter.run/extensions/cardano-dbsync-port" target="_blank">Deploy</a>
    </p>
</div>