<?php
/**
 * Veralidity, LLC
 *
 * @package    Veralidity
 * @category   CardanoDbSync
 * @copyright  Copyright © 2024 Veralidity, LLC
 * @license    https://www.veralidity.com/license/
 * @author     Veralidity, LLC <veralidity@protonmail.com>
 */
?>
<button class="scalable" type="button" id="<?= $block->getHtmlId() ?>" data-mage-init='{"testCardanoDbSyncConnection":{
    "url": "<?= $block->escapeUrl($block->getAjaxUrl()) ?>",
    "elementId": "<?= $block->getHtmlId() ?>",
    "successText": "<?= $block->escapeHtmlAttr(__('Successful! Test again?')) ?>",
    "failedText": "<?= $block->escapeHtmlAttr(__('Connection failed! Test again?')) ?>",
    "fieldMapping": "<?= /* @noEscape */ $block->getFieldMapping() ?>"}, "validation": {}}'>
    <span id="<?= $block->getHtmlId() ?>_result"><?= $block->escapeHtml($block->getButtonLabel()) ?></span>
</button>
<div class="scalable" id="blockchain-<?= $block->getHtmlId() ?>"></div>